# -*- coding: utf-8 -*-
"""10 days of statistics challange.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1EDyZF3cgj-BzFRTbcX3bha9jYqaxgfZ_

## Mean, Median and Mode
"""

import numpy as np
from scipy import stats

#Take input from user, It is the size of the N
size = int(input())
#Take numbers from user as input
numbers = list(map(int, input().split()))
print(np.mean(numbers))
print(np.median(numbers))
print(int(stats.mode(numbers)[0]))